// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log("Supabase URL loaded:", !!envUrl);
console.log("Supabase Key loaded:", !!envKey);

const SUPABASE_URL = (envUrl && envUrl.startsWith('http')) ? envUrl : "https://placeholder-project.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = envKey || "placeholder-key";

if (SUPABASE_URL === "https://placeholder-project.supabase.co") {
  console.warn("Supabase is using a placeholder URL. Please set VITE_SUPABASE_URL in your environment variables.");
}

const isPlaceholder = SUPABASE_URL === "https://placeholder-project.supabase.co";

// Cache the client instance to prevent "Lock broken by another request with the 'steal' option."
// during Vite HMR.
const globalForSupabase = globalThis as unknown as {
  supabase: ReturnType<typeof createClient<Database>> | undefined;
};

export const supabase =
  globalForSupabase.supabase ||
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: !isPlaceholder,
      autoRefreshToken: !isPlaceholder,
      detectSessionInUrl: !isPlaceholder,
    },
    global: {
      fetch: isPlaceholder
        ? async (url) => {
            console.warn("Supabase is using a placeholder URL. Mocking response.");
            const urlString = typeof url === 'string' ? url : url instanceof URL ? url.toString() : url.url;
            const isRest = urlString.includes('/rest/v1/');
            return new Response(JSON.stringify(isRest ? [] : {}), {
              status: 200,
              headers: { "Content-Type": "application/json" },
            });
          }
        : async (input, init) => {
            let lastError;
            for (let i = 0; i < 3; i++) {
              try {
                const response = await fetch(input, init);
                if (!response.ok) {
                  try {
                    const clone = response.clone();
                    const data = await clone.json();
                    const errorDesc = data?.error_description || data?.msg || data?.message || data?.error || "";
                    if (
                      errorDesc.toLowerCase().includes("refresh token") ||
                      errorDesc.toLowerCase().includes("invalid_grant") ||
                      errorDesc.toLowerCase().includes("session_not_found") ||
                      errorDesc.toLowerCase().includes("invalid_refresh_token")
                    ) {
                      console.warn("Intercepted invalid refresh token error, clearing session...");
                      const keysToRemove: string[] = [];
                      for (let j = 0; j < localStorage.length; j++) {
                        const key = localStorage.key(j);
                        if (key && (key.includes('supabase') || key.includes('sb-'))) {
                          keysToRemove.push(key);
                        }
                      }
                      keysToRemove.forEach(key => localStorage.removeItem(key));
                      sessionStorage.clear();
                      // Only redirect if we are not already on the auth page
                      if (!window.location.pathname.includes('/auth')) {
                        window.location.href = '/auth';
                      }
                    }
                  } catch {
                    // ignore JSON parse errors
                  }
                }
                return response;
              } catch (err) {
                lastError = err;
                await new Promise(resolve => setTimeout(resolve, 500 * (i + 1)));
              }
            }
            const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
            console.error("Supabase network error for URL:", url, "Error:", lastError);
            throw lastError;
          },
    },
  });

if (import.meta.env.DEV) {
  globalForSupabase.supabase = supabase;
}