export const DEFAULT_SEED_DATA: Record<string, Record<string, unknown>[]> = {
  home_sections: [
    {
      id: "sec-hero-1",
      section_key: "hero",
      display_order: 1,
      is_visible: true,
      section_data: {
        title: "Biomedical Engineering Society",
        subtitle: "CUET BMES",
        description: "Advancing healthcare through engineering innovation, interdisciplinary research, and student excellence.",
        button_text: "Join Society",
        button_link: "/portal?tab=membership",
      },
    },
    {
      id: "sec-quick-2",
      section_key: "quick_links",
      display_order: 2,
      is_visible: true,
      section_data: {
        links: [
          { label: "Notice Board", url: "/notices" },
          { label: "Academic Resources", url: "/academics" },
          { label: "Events & Workshops", url: "/events" },
          { label: "Member Directory", url: "/people" },
        ],
      },
    },
    {
      id: "sec-announce-3",
      section_key: "announcements",
      display_order: 3,
      is_visible: true,
      section_data: {
        dept_title: "Departmental Notices",
        club_title: "Society Updates",
      },
    },
    {
      id: "sec-events-4",
      section_key: "upcoming_events",
      display_order: 4,
      is_visible: true,
      section_data: {
        title: "Upcoming Events & Workshops",
        description: "Join our seminars, hackathons, and technical bootcamps.",
      },
    },
    {
      id: "sec-achieve-5",
      section_key: "recent_achievements",
      display_order: 5,
      is_visible: true,
      section_data: {
        title: "Recent Achievements & Milestones",
        description: "Recognizing international awards, research publications, and grants.",
      },
    },
    {
      id: "sec-projects-6",
      section_key: "featured_projects",
      display_order: 6,
      is_visible: true,
      section_data: {
        title: "Featured Biomedical Projects",
        description: "Pioneering prototypes, assistive technology, and clinical devices built by our students.",
      },
    },
    {
      id: "sec-blog-7",
      section_key: "recent_blog",
      display_order: 7,
      is_visible: true,
      section_data: {
        title: "Latest Articles & Insights",
        description: "Read perspectives on biomedical advancements and student research journeys.",
      },
    },
    {
      id: "sec-stats-8",
      section_key: "stats",
      display_order: 8,
      is_visible: true,
      section_data: {
        items: [
          { label: "Active Members", value: "350+" },
          { label: "Published Papers", value: "60+" },
          { label: "Workshops Conducted", value: "45+" },
          { label: "Global Alumni", value: "180+" },
        ],
      },
    },
    {
      id: "sec-cta-9",
      section_key: "cta",
      display_order: 9,
      is_visible: true,
      section_data: {
        title: "Ready to Shape the Future of Healthcare Engineering?",
        description: "Connect with faculty, collaborate on breakthrough biomedical projects, and access exclusive learning resources.",
        button_text: "Join CUET BMES",
        button_link: "/portal?tab=membership",
      },
    },
  ],

  site_settings: [
    { id: "s1", setting_key: "site_name", setting_value: "CUET Biomedical Engineering Society" },
    { id: "s2", setting_key: "home_hero_title", setting_value: "Biomedical Engineering Society" },
    { id: "s3", setting_key: "home_hero_subtitle", setting_value: "CUET BMES" },
    { id: "s4", setting_key: "home_hero_description", setting_value: "Advancing healthcare through engineering innovation, interdisciplinary research, and student excellence." },
    { id: "s5", setting_key: "home_hero_button_text", setting_value: "Join Society" },
    { id: "s6", setting_key: "home_hero_button_link", setting_value: "/portal?tab=membership" },
    { id: "s7", setting_key: "contact_email", setting_value: "bmes@cuet.ac.bd" },
    { id: "s8", setting_key: "contact_location", setting_value: "CUET, Chittagong-4349, Bangladesh" },
    {
      id: "s9",
      setting_key: "portal_notices_json",
      setting_value: JSON.stringify([
        {
          title: "Registration Open: 5th National Biomedical Hackathon 2026",
          date: "2026-09-15",
          category: "club",
          content: "Teams from engineering and medical universities across Bangladesh are invited to participate.",
        },
        {
          title: "Lab Schedule Update: Bio-Signal Processing & Instrumentation Lab",
          date: "2026-09-01",
          category: "departmental",
          content: "All undergraduate students must follow the revised schedule for fall semester practical sessions.",
        },
        {
          title: "Call for Papers: Annual Symposium on Medical Imaging & AI",
          date: "2026-08-20",
          category: "departmental",
          content: "Submit your original abstracts by September 30 for peer review.",
        },
      ]),
    },
  ],

  events: [
    {
      id: "evt-1",
      title: "Hands-on Bio-Signal Processing & EMG Bootcamp",
      description: "Comprehensive 2-day workshop on extracting, filtering, and classifying EMG & ECG signals using MATLAB and Python.",
      date: new Date(Date.now() + 7 * 86400000).toISOString(),
      location: "Biomedical Lab 3, Dept of BME, CUET",
      image_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80",
      type: "Workshop",
      is_upcoming: true,
      registration_open: true,
      max_participants: 60,
    },
    {
      id: "evt-2",
      title: "National Biomedical Innovation Expo & Seminar",
      description: "Showcasing student prototypes, keynote lectures from clinical directors, and industry panel discussions.",
      date: new Date(Date.now() + 21 * 86400000).toISOString(),
      location: "CUET Central Auditorium",
      image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80",
      type: "Seminar",
      is_upcoming: true,
      registration_open: true,
      max_participants: 250,
    },
    {
      id: "evt-3",
      title: "Medical 3D Printing & Prosthetics Workshop",
      description: "CAD modeling and additive manufacturing for customized orthopedic splints and upper-limb prosthetic sockets.",
      date: new Date(Date.now() + 35 * 86400000).toISOString(),
      location: "FabLab CUET",
      image_url: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=800&auto=format&fit=crop&q=80",
      type: "Hands-on Training",
      is_upcoming: true,
      registration_open: true,
      max_participants: 40,
    },
  ],

  achievements: [
    {
      id: "ach-1",
      title: "1st Place - Global Health Hackathon 2025",
      category: "competition",
      description: "Team CUET BMES designed an ultra-low-cost photoplethysmography sensor for rural maternal monitoring.",
      year: "2025",
      image_url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80",
    },
    {
      id: "ach-2",
      title: "IEEE EMBC Outstanding Student Branch Chapter Award",
      category: "award",
      description: "Recognized internationally for exceptional technical engagement, workshops, and community health camps.",
      year: "2025",
      image_url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80",
    },
    {
      id: "ach-3",
      title: "Research Grant for AI-driven Diagnostic Ultrasound",
      category: "grant",
      description: "Secured research funding from the Ministry of Science and Technology for developing lightweight ultrasound segmentation models.",
      year: "2024",
      image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80",
    },
  ],

  projects: [
    {
      id: "proj-1",
      title: "Non-Invasive Continuous Blood Glucose Monitor",
      description: "Near-infrared optical spectroscopy sensor paired with mobile telemetry for diabetic patient care.",
      category: "Medical Devices",
      progress: 90,
      tags: ["Spectroscopy", "Embedded Systems", "IoT"],
      image_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80",
    },
    {
      id: "proj-2",
      title: "Myoelectric Prosthetic Hand with Tactile Feedback",
      description: "3D-printed bionic hand utilizing surface EMG signals with embedded vibrotactile haptic actuators.",
      category: "Biomechanics & Robotics",
      progress: 85,
      tags: ["Prosthetics", "EMG", "Robotics"],
      image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    },
    {
      id: "proj-3",
      title: "Deep Learning for Automated Histopathology Screening",
      description: "Computer vision framework for fast detection of abnormal cell patterns in tissue biopsy scans.",
      category: "Bioinformatics & AI",
      progress: 75,
      tags: ["Deep Learning", "Microscopy", "Pathology"],
      image_url: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&auto=format&fit=crop&q=80",
    },
  ],

  blog_posts: [
    {
      id: "blog-1",
      slug: "future-of-neural-interfaces-in-rehabilitation",
      title: "The Future of Neural Interfaces in Motor Rehabilitation",
      summary: "Exploring recent breakthroughs in non-invasive brain-computer interfaces for stroke rehabilitation.",
      content: `## Bridging Neurology and Bio-Engineering\n\nMotor rehabilitation after stroke has entered a new era with high-density electroencephalography (EEG) and closed-loop neuromodulation...\n\n### Clinical Applications\nRecent studies show significant neuroplastic adaptation when biofeedback is delivered within 100 milliseconds of intention detection.`,
      category: "Neuroengineering",
      status: "published",
      featured_image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop&q=80",
      created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: "blog-2",
      slug: "microfluidics-lab-on-a-chip-revolution",
      title: "Lab-on-a-Chip: Revolutionizing Point-of-Care Diagnostics",
      summary: "How microfluidic channels and biosensors enable rapid infectious disease detection in resource-limited clinics.",
      content: `## Miniaturizing the Diagnostic Laboratory\n\nMicrofluidic devices manipulate microliter volumes of biological samples to perform biochemical assays with extreme speed and precision...`,
      category: "Biosensors",
      status: "published",
      featured_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80",
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
  ],

  people: [
    {
      id: "person-1",
      name: "Dr. Mohammad Hasan",
      role: "Head of Department & Chief Advisor",
      category: "faculty",
      email: "hasan@cuet.ac.bd",
      department: "Biomedical Engineering",
      image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
    },
    {
      id: "person-2",
      name: "Tahmid Rahman",
      role: "President, CUET BMES",
      category: "committee",
      email: "tahmid@cuet.ac.bd",
      department: "Biomedical Engineering",
      image_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
    },
    {
      id: "person-3",
      name: "Nusrat Jahan",
      role: "General Secretary",
      category: "committee",
      email: "nusrat@cuet.ac.bd",
      department: "Biomedical Engineering",
      image_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
    },
    {
      id: "person-4",
      name: "Arif Chowdhury",
      role: "Research & Development Lead",
      category: "committee",
      email: "arif@cuet.ac.bd",
      department: "Biomedical Engineering",
      image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
    },
  ],

  notices: [
    {
      id: "not-1",
      title: "Call for Executive Committee Nominations (Session 2026-2027)",
      content: "All eligible general members can submit their nomination forms for the upcoming executive committee election.",
      category: "General",
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: "not-2",
      title: "Biomedical Internship Placement Drive",
      content: "Partner hospitals and medical device manufacturers are opening internships for 3rd and 4th-year undergraduates.",
      category: "Career",
      created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  ],

  alumni: [
    {
      id: "alumni-1",
      name: "Dr. Farhana Ahmed",
      graduation_year: "2018",
      current_role: "Senior Biomedical Engineer at Siemens Healthineers",
      testimonial: "CUET BMES gave me the early lab exposure and research discipline that opened global opportunities in clinical medical technology.",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
      is_spotlight: true,
    },
    {
      id: "alumni-2",
      name: "Kazi Saiful Islam",
      graduation_year: "2020",
      current_role: "PhD Researcher in Neural Engineering, Johns Hopkins University",
      testimonial: "The project mentorship and supportive community at CUET BMES transformed my engineering curiosity into high-impact academic research.",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
      linkedin: "https://linkedin.com",
      is_spotlight: true,
    },
  ],
};
